CREATE TABLE profiles (
    id UUID PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    apellido_paterno TEXT,
    apellido_materno TEXT,
    empresa_id UUID NOT NULL,
    sede_id UUID,
    hierarchy TEXT NOT NULL CHECK (hierarchy IN ('super_admin',
    'admin_empresa',
    'medico_trabajo',
    'medico_especialista',
    'medico_industrial',
    'enfermera',
    'audiometrista',
    'psicologo_laboral',
    'recepcion',
    'paciente')),
    avatar_url TEXT,
    telefono TEXT,
    cedula_profesional TEXT,
    especialidad TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active',
    'inactive',
    'suspended')),
    login_count INTEGER DEFAULT 0,
    last_login_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}',
    preferences JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);